plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.greencix.citygo'
    compileSdk 36

    defaultConfig {
        applicationId "com.greencix.citygo"
        minSdk 28
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        viewBinding true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.appcompat
    implementation libs.material
    implementation libs.lottie
    implementation libs.activity
    implementation libs.fragment
    implementation libs.constraintlayout
    implementation libs.cardview

    // Map & Location & Media
    implementation libs.play.services.location
    implementation libs.osmdroid
    implementation libs.glide

    // Networking & Supabase REST client
    implementation libs.okhttp
    implementation libs.okhttp.logging
    implementation libs.gson

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}